class BiofastqA < Formula
  desc "High-performance FASTQ/FASTA quality analysis — written in Rust"
  homepage "https://github.com/DilaDeniz/BioFastq-a"
  url "https://github.com/DilaDeniz/BioFastq-a/archive/refs/tags/v2.1.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256_UPDATE_BEFORE_PUBLISHING"
  license "MIT"
  head "https://github.com/DilaDeniz/BioFastq-a.git", branch: "main"

  bottle do
    # Bottles are generated by the CI workflow after each release.
    # Run: brew test-bot --only-formulae biofastq-a
  end

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    # Write a minimal 4-read FASTQ and check that the tool runs headlessly
    (testpath/"test.fastq").write <<~FASTQ
      @read1
      ACGTACGTACGTACGT
      +
      IIIIIIIIIIIIIIII
      @read2
      TTTTTTTTTTTTTTTT
      +
      IIIIIIIIIIIIIIII
      @read3
      GCGCGCGCGCGCGCGC
      +
      IIIIIIIIIIIIIIII
      @read4
      AGATCGGAAGAGCACACGTCT
      +
      IIIIIIIIIIIIIIIIIIIII
    FASTQ

    system bin/"biofastq-a", "test.fastq", "--headless", "--output-dir", testpath
    assert_predicate testpath/"test_report.html", :exist?
    assert_predicate testpath/"test_report.json", :exist?
  end
end
